---
# Setup variables and facts.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - tools

- import_tasks: setup/variables.yml
  tags:
    - tools

# Install
- include_tasks: setup/packages.yml
  tags:
    - tools

# Configuration
- include_tasks: config/hostname.yml
  tags:
    - tools

- include_tasks: config/motd.yml
  tags:
    - tools

- include_tasks: config/prompt.yml
  tags:
    - tools

- include_tasks: config/ssh.yml
  tags:
    - tools
